import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from '../components/layout/Navbar'
import Footer from '../components/layout/Footer'
import { montserrat, donpoligrafbum } from "./fonts";


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${montserrat.variable} ${donpoligrafbum.variable}`} >
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
